import { createStore } from "vuex";

export default createStore({
  state: {
    loginStatus: false,
    skins: [
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Gamma Doppler Emerald',
        category: 'Необычайно редкие',
        color: '#F6C744',
        img: 'https://s1.cs.money/fd45ff83324b4f6d7b69c1a392fd6bd8_large_preview.png',
        game: 'cs',
        count: 9,
        price: 17539,
        isAble: false,
        data: '6д 3ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Snow Leopard',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://s1.cs.money/ff079faee9abce63d99bae6b342d6232_large_preview.png',
        game: 'cs',
        count: 19,
        price: 14858,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Dragon Lore',
        category: 'Армейские',
        color: '#275CE4',
        img: 'https://s1.cs.money/d02c3a6923ca2539b45629bfaaf0d63b_large_preview.png',
        game: 'cs',
        count: 200,
        price: 6245,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Ruby',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://s1.cs.money/e6e402910659e78701ca4de996f7041a_large_preview.png',
        game: 'cs',
        count: 6,
        price: 8593,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Gungnir',
        category: 'Засекреченные',
        color: '#CF309C',
        img: 'https://s1.cs.money/118ef2030d7c5a940518f6a3299862c9_large_preview.png',
        game: 'cs',
        count: 21,
        price: 7026,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Spearmint',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://s1.cs.money/3e7eb95f9d71f258b353a5cd0593f1e9_large_preview.png',
        game: 'cs',
        count: 25,
        price: 7025,
        isAble: false,
        data: '7д 1ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Dragon Lore ',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://s1.cs.money/11000a791247232a1d7caa01fce42fe6_large_preview.png',
        game: 'cs',
        count: 40,
        price: 5907,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Cobalt Skulls',
        category: 'Засекреченные',
        color: '#CF309C',
        img: 'https://s1.cs.money/89c41fc83e1d094513a3edaf02b07a4e_large_preview.png',
        game: 'cs',
        count: 19,
        price: 2839,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Ruby',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://s1.cs.money/28c2327280eea119f4637400d613602d_large_preview.png',
        game: 'cs',
        count: 1,
        price: 5999,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Howl',
        category: 'Необычайно редкие',
        color: '#F6C744',
        img: 'https://s1.cs.money/d0da1cca3eb832a3e970136b437369a0_large_preview.png',
        game: 'cs',
        count: 10,
        price: 17909,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Sapphire',
        category: 'Запрещенные',
        color: '#8533ED',
        img: 'https://s1.cs.money/e377d64681bbddea264e54d67c892d1b_large_preview.png',
        game: 'cs',
        count: 8,
        price: 10500,
        isAble: false,
        data: '18д 15ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Crimson Kimono',
        category: 'Армейские',
        color: '#275CE4',
        img: 'https://s1.cs.money/85dec624ddac61a07ef01b81ce31326c_large_preview.png',
        game: 'cs',
        count: 19,
        price: 6500,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Tiger Strike',
        category: 'Промышленные',
        color: '#6AB2F4',
        img: 'https://s1.cs.money/d1ea23a888bb15220130ad6fa740f360_large_preview.png',
        game: 'cs',
        count: 28,
        price: 5500,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Sapphire',
        category: 'Ширпотреб',
        color: '#B4C2D7',
        img: 'https://s1.cs.money/fdfedd8cf7d884f10f2fbac25d096148_large_preview.png',
        game: 'cs',
        count: 5,
        price: 3500,
        isAble: false,
        data: '13ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Gamma Doppler Emerald',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://s1.cs.money/fd45ff83324b4f6d7b69c1a392fd6bd8_large_preview.png',
        game: 'cs',
        count: 35,
        price: 17500,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Sapphire',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://s1.cs.money/e377d64681bbddea264e54d67c892d1b_large_preview.png',
        game: 'cs',
        count: 10,
        price: 16200,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Crimson Web ',
        category: 'Засекреченные',
        color: '#CF309C',
        img: 'https://s1.cs.money/dce921b4ca87fdb6c4fb4978722613d1_large_preview.png',
        game: 'cs',
        count: 80,
        price: 14200,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Crimson Web ',
        category: 'Запрещенные',
        color: '#8533ED',
        img: 'https://s1.cs.money/86d692c732151cb3a4bafd0b29637d81_large_preview.png',
        game: 'cs',
        count: 6,
        price: 13900,
        isAble: false,
        data: '15д',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Slingshot',
        category: 'Необычайно редкие',
        color: '#F6C744',
        img: 'https://s1.cs.money/ca3ed3d4114926583f14c4e0e78d02b5_large_preview.png',
        game: 'cs',
        count: 18,
        price: 12000,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Crimson Kimono',
        category: 'Необычайно редкие',
        color: '#F6C744',
        img: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DAQ1h3LAVbv6mxFABs3OXNYgJR_Nm1nYGHnuTgDLDYm2Rf5_p1g-jM-oLxm2umrhcDPzCkfMKLewY8NVDZ_le8x7ztjJbqusvJmCdgsiYlsH3cmR2zhB1NZ-JogvGXQULeWfLIJRig1Q',
        game: 'cs',
        count: 1,
        price: 22000,
        isAble: false,
        data: '5д 12ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Dragon Lore',
        category: 'Необычайно редкие',
        color: '#F6C744',
        img: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot621FAR17P7NdTRH-t26q4SZlvD7PYTQgXtu5Mx2gv2P9o6migzl_Us5ZmCmLYDDJgU9NA6B81S5yezvg8e-7cycnXJgvHZx5WGdwUJqz1Tl4g',
        game: 'cs',
        count: 100,
        price: 10400,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Sapphire ',
        category: 'Армейские',
        color: '#275CE4',
        img: 'https://s1.cs.money/d1ea23a888bb15220130ad6fa740f360_large_preview.png',
        game: 'cs',
        count: 320,
        price: 9000,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Ruby',
        category: 'Промышленные',
        color: '#6AB2F4',
        img: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposbaqKAxf0vL3dzxG6eO6nYeDg7miYr7VlWgHscN32LyT8dmm31XgrxdtZzvzJYDGIFM2Y16D-FfvlOu9m9bi66Oq9HyE',
        game: 'cs',
        count: 110,
        price: 7505,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Spearmint',
        category: 'Ширпотреб',
        color: '#B4C2D7',
        img: 'https://s1.cs.money/3e7eb95f9d71f258b353a5cd0593f1e9_large_preview.png',
        game: 'cs',
        count: 440,
        price: 7335,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Ruby',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJf3qr3czxb49KzgL-KmsjmJrnIqWZQ-sd9j-Db8IjKhF2zowdyYzjyLIGSIAA8YguCqVK9lOa-1JW5vprBz3EyviB07SveyhfkhklNP_sv26JLM0iiyQ',
        game: 'cs',
        count: 50,
        price: 17258,
        isAble: false,
        data: '10д 2ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Medusa',
        category: 'Засекреченные',
        color: '#CF309C',
        img: 'https://s1.cs.money/48891b3d839c9dab957a17f2966ddf3e_large_preview.png',
        game: 'cs',
        count: 90,
        price: 9282,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Gold Arabesque',
        category: 'Запрещенные',
        color: '#8533ED',
        img: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhnwMzJemkV09u5mIS0luX1Mb7Ch35U18h0juDU-MKn3lC2rkRqaj-iLYPDcAJsYVyBqFO_yee-h5Xq6Z7InyQ1uCMq5yzYgVXp1rYILQK0',
        game: 'cs',
        count: 105,
        price: 1499,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Pandora`s Box',
        category: 'Промышленные',
        color: '#6AB2F4',
        img: 'https://s1.cs.money/a44e27ec91c304be5c29042cd2cf2d3d_large_preview.png',
        game: 'cs',
        count: 203,
        price: 4058,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Sapphire',
        category: 'Засекреченные',
        color: '#CF309C',
        img: 'https://s1.cs.money/d40610e90ee108dc1240bce539266d7a_large_preview.png',
        game: 'cs',
        count: 25,
        price: 9045,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Gamma Doppler Emerald',
        category: 'Ширпотреб',
        color: '#B4C2D7',
        img: 'https://s1.cs.money/7b141cccac4cf625c794fdaeababb17a_large_preview.png',
        game: 'cs',
        count: 210,
        price: 3126,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Cool Mint',
        category: 'Ширпотреб',
        color: '#B4C2D7',
        img: 'https://s1.cs.money/2b892c6919d4b0e9ac4c35088f764632_large_preview.png',
        game: 'cs',
        count: 210,
        price: 2519,
        isAble: false,
        data: '5д 2ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Imminent Danger',
        category: 'Промышленные',
        color: '#6AB2F4',
        img: 'https://s1.cs.money/fdf7820916c4cee5ac04b5a77fae2249_large_preview.png',
        game: 'cs',
        count: 400,
        price: 1150,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Crimson Web',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://s1.cs.money/bf53d328808a51a1243ca4e2e61d03d4_large_preview.png',
        game: 'cs',
        count: 26,
        price: 2999,
        isAble: false,
        data: '2д 3ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Autotronic',
        category: 'Армейские',
        color: '#275CE4',
        img: 'https://s1.cs.money/82d752500145742402fe9741617b4c85_large_preview.png',
        game: 'cs',
        count: 24,
        price: 2006,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'POW!',
        category: 'Засекреченные',
        color: '#CF309C',
        img: 'https://s1.cs.money/bf53d328808a51a1243ca4e2e61d03d4_large_preview.png',
        game: 'cs',
        count: 45,
        price: 2019,
        isAble: false,
        data: '1д',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Autotronic',
        category: 'Необычайно редкие',
        color: '#F6C744',
        img: 'https://s1.cs.money/5a0d26f694aaa76eaaf86eafc31b22ca_large_preview.png',
        game: 'cs',
        count: 4,
        price: 6019,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },

      {
        id: Math.random().toString().substr(2, 6),
        title: 'Fade',
        category: 'Запрещенные',
        color: '#8533ED',
        img: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJfwPjNfThW49KJlYG0kfbwNoTdn2xZ_Ish3LyQotugjlXmr0NpZmjwIY_AIQ84ZF3ZrFi2wu26h57q7Z3OwHNkpGB8spXTbTbn',
        game: 'cs',
        count: 58,
        price: 2506,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Snow Leopard',
        category: 'Запрещенные',
        color: '#8533ED',
        img: 'https://s1.cs.money/63a9e18e23d68e549d55d92273654e72_large_preview.png',
        game: 'cs',
        count: 450,
        price: 2397,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Night',
        category: 'Тайные',
        color: '#ED422B',
        img: 'https://steamcommunity-a.akamaihd.net/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJf0ebcZThQ6tCvq5OEqPn9NLPFqWdY781lxLDHp9mh3Ffn_ktqZDj2IIbDc1I-MF2F_lW4le_v0ZW57pmbm3FhuiI8pSGKaAesdpc',
        game: 'cs',
        count: 40,
        price: 2500,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Black Laminate',
        category: 'Армейские',
        color: '#275CE4',
        img: 'https://s1.cs.money/8b5ae35959edd342d4e8357f7ba97eab_large_preview.png',
        game: 'cs',
        count: 250,
        price: 1209,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Ultraviolet',
        category: 'Засекреченные',
        color: '#CF309C',
        img: 'https://s1.cs.money/f024cb85dd4f346dccfe90bfe2b69e8d_large_preview.png',
        game: 'cs',
        count: 25,
        price: 4109,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Doppler Sapphire',
        category: 'Армейские',
        color: '#275CE4',
        img: 'https://s1.cs.money/e2e2c2a576dca7b80ca639227eca98bd_large_preview.png',
        game: 'cs',
        count: 251,
        price: 3630,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Lore',
        category: 'Запрещенные',
        color: '#8533ED',
        img: 'https://s1.cs.money/aa7c82f4e6841903edffd53e98956674_large_preview.png',
        game: 'cs',
        count: 405,
        price: 4389,
        isAble: false,
        data: '5д 15ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Howl',
        category: 'Промышленные',
        color: '#6AB2F4',
        img: 'https://s1.cs.money/bb0941e7432a9f317307f4429c4f583b_large_preview.png',
        game: 'cs',
        count: 251,
        price: 3810,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },













      ///////////////////////////////////////////////////////////////////////////////////////
      ////////////////////////////////////////////////////////////////////////////////////////
      // dota /////////////////////////////////

      {
        id: Math.random().toString().substr(2, 6),
        title: 'Town Portal Scroll',
        category: 'Arcana',
        color: '#4ADD32',
        img: 'https://dota2.ru/img/items/observer_and_sentry_wards.jpg?1661242182',
        game: 'dota',
        count: 11,
        price: 16810,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Magic Wand',
        category: 'Immortal',
        color: '#FFCE50',
        img: 'https://dota2.ru/img/items/magic_wand.jpg?1665327757',
        game: 'dota',
        count: 1,
        price: 16100,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Blade of Alacrity',
        category: 'Legendary',
        color: '#CF309C',
        img: 'https://dota2.ru/img/items/blade_of_alacrity.jpg?1660228956',
        game: 'dota',
        count: 13,
        price: 10100,
        isAble: false,
        data: '20ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Mithril Hammer',
        category: 'Mythical',
        color: '#8533ED',
        img: 'https://dota2.ru/img/items/mithril_hammer.jpg?1663668256',
        game: 'dota',
        count: 5,
        price: 7020,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Arcane Blink',
        category: 'Arcana',
        color: '#4ADD32',
        img: 'https://dota2.ru/img/items/arcane_blink.jpg?1645741080',
        game: 'dota',
        count: 9,
        price: 17020,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Ring of Health',
        category: 'Uncommon',
        color: '#6AB2F4',
        img: 'https://dota2.ru/img/items/ring_of_health.jpg?1608360499',
        game: 'dota',
        count: 90,
        price: 1020,
        isAble: false,
        data: '3д 3ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Mage Slayer',
        category: 'Immortal',
        color: '#FFCE50',
        img: 'https://dota2.ru/img/items/mage_slayer.jpg?1661324877',
        game: 'dota',
        count: 27,
        price: 10200,
        isAble: false,
        data: '5д  3ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Hood of Defiance',
        category: 'Common',
        color: '#B4C2D7',
        img: 'https://dota2.ru/img/items/hood_of_defiance.jpg?1645918469',
        game: 'dota',
        count: 7,
        price: 1020,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Swift Blink',
        category: 'Immortal',
        color: '#FFCE50',
        img: 'https://dota2.ru/img/items/swift_blink.jpg?1645922393',
        game: 'dota',
        count: 5,
        price: 12090,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },

      {
        id: Math.random().toString().substr(2, 6),
        title: 'Blight Stone',
        category: 'Rare',
        color: '#275CE4',
        img: 'https://dota2.ru/img/items/blight_stone.jpg?1663517482',
        game: 'dota',
        count: 50,
        price: 5090,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Belt of Strength',
        category: 'Legendary',
        color: '#CF309C',
        img: 'https://dota2.ru/img/items/vladmirs_offering.jpg?1667156876',
        game: 'dota',
        count: 40,
        price: 8090,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Observer',
        category: 'Uncommon',
        color: '#6AB2F4',
        img: 'https://dota2.ru/img/items/observer_and_sentry_wards.jpg?1661242182',
        game: 'dota',
        count: 200,
        price: 5200,
        isAble: false,
        data: '1д 17ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Clarity',
        category: 'Mythical',
        color: '#8533ED',
        img: 'https://dota2.ru/img/items/belt_of_strength.jpg?1661168777',
        game: 'dota',
        count: 40,
        price: 9090,
        isAble: false,
        data: '14д 5ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Faerie Fire',
        category: 'Immortal',
        color: '#FFCE50',
        img: 'https://dota2.ru/img/items/faerie_fire.jpg?1660039784',
        game: 'dota',
        count: 24,
        price: 7090,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Smoke of Deceit',
        category: 'Common',
        color: '#B4C2D7',
        img: 'https://dota2.ru/img/items/smoke_of_deceit.jpg?1660039814',
        game: 'dota',
        count: 250,
        price: 1090,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Dagon',
        category: 'Arcana',
        color: '#4ADD32',
        img: 'https://dota2.ru/img/items/dagon.jpg?1668507920',
        game: 'dota',
        count: 25,
        price: 11200,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Oblivion Staff',
        category: 'Immortal',
        color: '#FFCE50',
        img: 'https://dota2.ru/img/items/oblivion_staff.jpg?1666021500',
        game: 'dota',
        count: 51,
        price: 15200,
        isAble: false,
        data: '10д 15м',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Solar Crest',
        category: 'Rare',
        color: '#275CE4',
        img: 'https://dota2.ru/img/items/solar_crest.jpg?1668517095',
        game: 'dota',
        count: 120,
        price: 10200,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Boots of Bearing',
        category: 'Arcana',
        color: '#4ADD32',
        img: 'https://dota2.ru/img/items/boots_of_bearing.jpg?1669799999',
        game: 'dota',
        count: 8,
        price: 20200,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Sage Mask',
        category: 'Uncommon',
        color: '#6AB2F4',
        img: 'https://dota2.ru/img/items/sages_mask.jpg?1663663740',
        game: 'dota',
        count: 800,
        price: 2090,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },

      {
        id: Math.random().toString().substr(2, 6),
        title: 'Gauntlets of Strength',
        category: 'Common',
        color: '#B4C2D7',
        img: 'https://dota2.ru/img/items/gauntlets_of_strength.jpg?1660822568',
        game: 'dota',
        count: 234,
        price: 1090,
        isAble: false,
        data: '3ч 15м',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Helm of the Overlord',
        category: 'Legendary',
        color: '#CF309C',
        img: 'https://dota2.ru/img/items/helm_of_the_overlord.jpg?1666442035',
        game: 'dota',
        count: 34,
        price: 10090,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Phase Boots',
        category: 'Mythical',
        color: '#8533ED',
        img: 'https://dota2.ru/img/items/phase_boots.jpg?1666043772',
        game: 'dota',
        count: 45,
        price: 11000,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },

      {
        id: Math.random().toString().substr(2, 6),
        title: 'Broadsword',
        category: 'Rare',
        color: '#275CE4',
        img: 'https://dota2.ru/img/items/broadsword.jpg?1603099255',
        game: 'dota',
        count: 85,
        price: 7500,
        isAble: false,
        data: '4д 1ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Null Talisman',
        category: 'Mythical',
        color: '#8533ED',
        img: 'https://dota2.ru/img/items/null_talisman.jpg?1665327942',
        game: 'dota',
        count: 84,
        price: 4590,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Javelin',
        category: 'Common',
        color: '#B4C2D7',
        img: 'https://dota2.ru/img/items/javelin.jpg?1664102465',
        game: 'dota',
        count: 550,
        price: 8650,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Kaya and Sange',
        category: 'Arcana',
        color: '#4ADD32',
        img: 'https://dota2.ru/img/items/sacred_relic.jpg?1631350450',
        game: 'dota',
        count: 5,
        price: 16650,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },

      {
        id: Math.random().toString().substr(2, 6),
        title: 'Orb of Venom',
        category: 'Legendary',
        color: '#CF309C',
        img: 'https://dota2.ru/img/items/orb_of_venom.jpg?1663518244',
        game: 'dota',
        count: 20,
        price: 8090,
        isAble: false,
        data: '1д 3ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Sacred Relic',
        category: 'Rare',
        color: '#275CE4',
        img: 'https://dota2.ru/img/items/gem_of_true_sight.jpg?1664807299',
        game: 'dota',
        count: 50,
        price: 6550,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Chainmail',
        category: 'Mythical',
        color: '#8533ED',
        img: 'https://dota2.ru/img/items/chainmail.jpg?1664084074',
        game: 'dota',
        count: 48,
        price: 5950,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Fluffy Hat',
        category: 'Rare',
        color: '#275CE4',
        img: 'https://dota2.ru/img/items/fluffy_hat.jpg?1663941925',
        game: 'dota',
        count: 84,
        price: 4590,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Swift Blink',
        category: 'Arcana',
        color: '#4ADD32',
        img: 'https://dota2.ru/img/items/swift_blink.jpg?1645922393',
        game: 'dota',
        count: 14,
        price: 15005,
        isAble: false,
        data: '1д 18ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Wind Lace',
        category: 'Uncommon',
        color: '#6AB2F4',
        img: 'https://dota2.ru/img/items/wind_lace.jpg?1664188427',
        game: 'dota',
        count: 104,
        price: 2545,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Guardian Greaves',
        category: 'Immortal',
        color: '#FFCE50',
        img: 'https://dota2.ru/img/items/guardian_greaves.jpg?1669820306',
        game: 'dota',
        count: 18,
        price: 11155,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },

      {
        id: Math.random().toString().substr(2, 6),
        title: 'Perseverance',
        category: 'Mythical',
        color: '#8533ED',
        img: 'https://dota2.ru/img/items/perseverance.jpg?1666021885',
        game: 'dota',
        count: 48,
        price: 8089,
        isAble: false,
        data: '12д 8ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Ogre Axe',
        category: 'Uncommon',
        color: '#6AB2F4',
        img: 'https://dota2.ru/img/items/ogre_axe.jpg?1663308379',
        game: 'dota',
        count: 96,
        price: 3082,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Rod of Atos',
        category: 'Legendary',
        color: '#CF309C',
        img: 'https://dota2.ru/img/items/rod_of_atos.jpg?1667926345',
        game: 'dota',
        count: 52,
        price: 5505,
        isAble: true,
        data: '',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Radiance',
        category: 'Rare',
        color: '#275CE4',
        img: 'https://dota2.ru/img/items/radiance.jpg?1669534724',
        game: 'dota',
        count: 72,
        price: 4029,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Null Talisman',
        category: 'Common',
        color: '#B4C2D7',
        img: 'https://dota2.ru/img/items/null_talisman.jpg?1665327942',
        game: 'dota',
        count: 175,
        price: 2050,
        isAble: false,
        data: '2д 2ч',
        firePrice: false,
        inventar: false,
      },
      {
        id: Math.random().toString().substr(2, 6),
        title: 'Orb of Corrosion',
        category: 'Mythical',
        color: '#8533ED',
        img: 'https://dota2.ru/img/items/orb_of_corrosion.jpg?1665393666',
        game: 'dota',
        count: 44,
        price: 4076,
        isAble: true,
        data: '',
        firePrice: true,
        inventar: false,
      },

    ],
    eventUser: {},
    users: [
      {
        id: Math.random().toString().substr(2, 6),
        name: 'Amirkhan',
        surname: 'Akhtamov',
        mail: 'Amirxan8482@gmail.com',
        password: 'amirxan8482',
        money: '999',
        cart: [],
        site: 'https://khanteam.netlify.app/',
        phone: '+998917013043',
      },
      {
        id: Math.random().toString().substr(2, 6),
        name: 'Khakim',
        surname: 'Almamedov',
        mail: 'Khalmamedov@gmail.com',
        password: 'almamedov2003',
        money: '500',
        cart: [],
        site: 'https://www.instagram.com/khakim.don/',
        phone: '+998915491754',
      },
      {
        id: Math.random().toString().substr(2, 6),
        name: 'Amir',
        surname: 'Axtamov',
        mail: '1',
        password: '1',
        money: '200',
        cart: [],
        site: 'https://www.instagram.com/mc_khan1/',
        phone: '+998938507334',
      },
      {
        id: Math.random().toString().substr(2, 6),
        name: 'Raul',
        surname: 'Raupov',
        mail: 'raupov@gmail.com',
        password: 'raulrp20006',
        money: '800',
        cart: [],
        site: 'https://www.instagram.com/roleydevv/',
        phone: '+998915685858',
      },
    ],

    category: [],
    redkost: [],
    allCategories: [],

    fallbackSkins: [],

    allGames: [
      {
        gameLogo: 'https://www.meme-arsenal.com/memes/84d612ba24c62550573a3bdbf0a58c29.jpg',
        gameName: 'cs',
        gameTitle: 'CS:GO'
      },
      {
        gameLogo: 'https://www.meme-arsenal.com/memes/89ab53e6d20d0a1b6d9ead1723311cd0.jpg',
        gameName: 'dota',
        gameTitle: 'DOTA 2'
      },
    ],

    inventory: [],


  },
  getters: {
    skins: (state) => state.skins,
    loginStatus: (state) => state.loginStatus,
    eventUser: (state) => state.eventUser,
    allGames: (state) => state.allGames,
    redkost: (state) => state.redkost,
    fallbackSkins: (state) => state.fallbackSkins,
    allCategories: (state) => state.allCategories,
    inventory: (state) => state.inventory,
  },
  mutations: {

    CAT__MUTATION(state) {


      state.fallbackSkins = state.skins

      // пополнение массива с названиями игр
      for (let i of state.skins) {
        state.category.push(i.game)
        // console.log(state.category);
      }


      // удалить повторяюшиеся элементы
      state.category = [...new Set(state.category)]

      // глобальная фильрация товаров на новый массив allCategories
      for (let i of state.category) {

        let obj = {
          id: Math.random().toString().substr(2, 6),
          game: i,
          arr: [],
          skinNames: []
        }
        state.allCategories.push(obj)

      }
      // пополнение массива с товарами игр, мисол учун дота буса дота обекти ичия кушабиз, кс буса кси ичия
      for (let i of state.skins) {
        for (let j of state.allCategories) {
          if (i.game == j.game) {
            j.arr.push(i)
          }
        }
      }

      // хар битта уйни ичидаги категорияларини сортировка килиб аккуратно массиви ичия куябиз
      for (let i of state.allCategories) {
        for (let j of i.arr) {
          // i.arr каней через пуш ми учун
          state.redkost.push(
            {
              gameName: j.game,
              categoryName: j.category
            }
          )
        }
      }
      // попоолнение skinNames внутри allCategories. skinNames ичида категориялари тихиб чикдик 
      for (let i of state.redkost) {
        for (let j of state.allCategories) {
          if (j.game == i.gameName) {
            j.skinNames.push(
              {
                categoryName: i.categoryName,
                items: [],
              }
            )
          }
        }
      }
      // удаляем повторяюшиеся элементы
      for (let i of state.allCategories) {
        let res = i.skinNames.reduce((o, i) => {
          if (!o.find(v => v.categoryName == i.categoryName)) {
            o.push(i);
          }
          return o;
        }, []);
        i.skinNames = res
      }

      for (let i of state.allCategories) {
        for (let j of i.arr) {
          for (let k of i.skinNames) {
            if (j.category == k.categoryName) {
              k.items.push(j)
            }
          }
        }
      }

    },

    PROVER__MUTATION(state, check) {
      for (let i of state.users) {
        if (i.mail == check.email && i.password == check.password) {
          state.eventUser = i
          state.loginStatus = true
          console.log(`${i.name} `);
        }
      }
    },
    ADD_INVENTORY__MUTATION(state, i) {
      for (let skin of state.skins) {
        if (skin == i) {
          skin.inventar = !skin.inventar
          

          if (skin.inventar) {
            state.inventory.push(skin)
          } else {
            state.inventory.splice(state.inventory.indexOf(skin), 1)
          }
        }
        
      }
    },
    CLEAR__MUTATION(state){
      state.inventory = []
      for(let i of state.skins){
        i.inventar = false
      }
    },
    REMOVE_IN_INVENTAR__MUTATION(state, item){
      for(let i of state.skins){
        if(i.id == item.id){
          i.inventar = false
          if(state.inventory.includes(i)){
            state.inventory.splice(state.inventory.indexOf(i), 1)
          }
        }
      }
    },
    SELECT_ALL__MUTATION(state, showSkinsFallback){
      state.inventory = []
      for(let i of showSkinsFallback){
        i.inventar = true
        if(i.isAble){
          state.inventory.push(i)
        }
      }
    }
  },
  actions: {
    PROVER({ commit }, check) {
      commit('PROVER__MUTATION', check)
    },
    CAT({ commit }) {
      commit('CAT__MUTATION')
    },
    ADD_INVENTORY({ commit }, i) {
      commit('ADD_INVENTORY__MUTATION', i)
    },
    CLEAR({ commit }) {
      commit('CLEAR__MUTATION')
    },
    REMOVE_IN_INVENTAR({ commit }, item) {
      commit('REMOVE_IN_INVENTAR__MUTATION', item)
    },
    SELECT_ALL({ commit }, showSkinsFallback) {
      commit('SELECT_ALL__MUTATION', showSkinsFallback)
    },
  },
});


